SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

IF COL_LENGTH('dbo.DanhMuc', 'Icon') IS NOT NULL
BEGIN
    ALTER TABLE dbo.DanhMuc ALTER COLUMN Icon NVARCHAR(100) NULL;
END

COMMIT TRANSACTION;
